### ISSUE TITLE
FastTiger - Due to lack of validation in the `FaultDisputeGame.sol#initialize()` function, duplicate checking in the `DisputeGameFactory.sol#create()` function can be bypassed.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#112]
FastTiger

medium

# Due to lack of validation in the `FaultDisputeGame.sol#initialize()` function, duplicate checking in the `DisputeGameFactory.sol#create()` function can be bypassed.

## Summary
By being able to bypass the duplicate check in the `DisputeGameFactory.sol#create()` function, it is possible to create multiple FDGs for the same claim, thus potentially allowing incorrectly resolved FDGs to be used in the protocol.
## Vulnerability Detail
In the `DisputeGameFactory.sol#create()` function, a duplicate check is performed to prevent FDGs from being duplicated.
```solidity
    function create(
        GameType _gameType,
        Claim _rootClaim,
        bytes calldata _extraData
    )
        external
        payable
        returns (IDisputeGame proxy_)
    {
        // Grab the implementation contract for the given `GameType`.
        IDisputeGame impl = gameImpls[_gameType];

        // If there is no implementation to clone for the given `GameType`, revert.
        if (address(impl) == address(0)) revert NoImplementation(_gameType);

        // If the required initialization bond is not met, revert.
        if (msg.value != initBonds[_gameType]) revert IncorrectBondAmount();

        // Get the hash of the parent block.
        bytes32 parentHash = blockhash(block.number - 1);

        // Clone the implementation contract and initialize it with the given parameters.
106:    proxy_ = IDisputeGame(address(impl).clone(abi.encodePacked(_rootClaim, parentHash, _extraData)));
107:    proxy_.initialize{ value: msg.value }();

        // Compute the unique identifier for the dispute game.
110:    Hash uuid = getGameUUID(_gameType, _rootClaim, _extraData);

        // If a dispute game with the same UUID already exists, revert.
113:    if (GameId.unwrap(_disputeGames[uuid]) != bytes32(0)) revert GameAlreadyExists(uuid);

        // Pack the game ID.
        GameId id = LibGameId.pack(_gameType, Timestamp.wrap(uint64(block.timestamp)), proxy_);

        // Store the dispute game id in the mapping & emit the `DisputeGameCreated` event.
        _disputeGames[uuid] = id;
        _disputeGameList.push(id);
        emit DisputeGameCreated(address(proxy_), _gameType, _rootClaim);
    }
```
However, due to the lack of validation of the `FaultDisputeGame.sol#initialize()` function, anyone can call it.
As a result, duplicate checking can be bypassed.
Below I will present the code for the attack scenario.
```solidity
contract Attack is IDisputeGameFactory {
    function createAttack(
        GameType _gameType,
        Claim _rootClaim,
        bytes calldata _extraData
    )
        external
        payable
        returns (IDisputeGame proxy_)
    {
        // Grab the implementation contract for the given `GameType`.
        IDisputeGame impl = gameImpls[_gameType];

        // If there is no implementation to clone for the given `GameType`, revert.
        if (address(impl) == address(0)) revert NoImplementation(_gameType);

        // If the required initialization bond is not met, revert.
        if (msg.value != initBonds[_gameType]) revert IncorrectBondAmount();

        // Get the hash of the parent block.
        bytes32 parentHash = blockhash(block.number - 1);

        // Clone the implementation contract and initialize it with the given parameters.
        proxy_ = IDisputeGame(address(impl).clone(abi.encodePacked(_rootClaim, parentHash, _extraData)));
        proxy_.initialize{ value: msg.value }();

        // Compute the unique identifier for the dispute game.
        Hash uuid = getGameUUID(_gameType, _rootClaim, _extraData);

        // Pack the game ID.
        GameId id = LibGameId.pack(_gameType, Timestamp.wrap(uint64(block.timestamp)), proxy_);

        // Store the dispute game id in the mapping & emit the `DisputeGameCreated` event.
        _disputeGames[uuid] = id;
        _disputeGameList.push(id);
        emit DisputeGameCreated(address(proxy_), _gameType, _rootClaim);
    }
}
```
As a result, there may be multiple FDGs for one claim in the protocol, and as a result, there is a potential risk such as using an FDG that has been incorrectly resolved in the protocol.
## Impact
There is a potential risk such as using an FDG that has been incorrectly resolved in the protocol.
## Code Snippet
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L513
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L84
## Tool used

Manual Review

## Recommendation
Implement the `FaultDisputeGame.sol#initialize()` function so that only DisputeGameFactory can call it.

**Comment by FastTiger777** [comment]
I think `proxy_` is different for each call even parameters are same in #L106. Therefore, the `initialized` of each `proxy_` is `false`.
As a result, even if `_rootClaim` is same, `proxy_` may be different. Could you please check again?

**Comment by FastTiger777** [comment]
> If the same parameters (`_rootClaim`, `parentHash`, `_extraData`) are passed each time this line of code is executed, the resulting contract address returned by the `clone` function would be different for each call. This is because each contract instance created using the `clone` function will have a unique address, even if the parameters passed are the same.
Therefore, if the parameters are the same but the code is called multiple times, the return address would be different for each call, resulting in multiple contract instances with unique addresses.

**Comment by FastTiger777** [comment]
After creating FDG in normal operation, run the attack code I suggested.

**Comment by nevillehuang** [comment]
@FastTiger777 I am not sure what you are referring to here. Once you deploy a new FDG, the factory contract will automatically initialize the FDG as seen [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L107), and thus that particular FDG contract cannot be initialized again due to the check [here](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L526). The optimism team will not deploy a new and separate factory contract.

**Comment by FastTiger777** [comment]
What i mean is that "There may be multiple FDGs for one claim in the protocol, and as a result, there is a potential risk such as using an FDG that has been incorrectly resolved in the protocol". So FDG incorrectly resolved in the protocol.
