### ISSUE TITLE
FassiSecurity - Corrupted data when creating a new game

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#115]
FassiSecurity

medium

# Corrupted data when creating a new game

## Summary
Due to unlimited `_extraData`, data can be corrupted in games leading to non-functionality.

## Vulnerability Detail
A person can create a new game using the `create()` function:
```javascript=
    function create(
        GameType _gameType,
        Claim _rootClaim,
->      bytes calldata _extraData
    )

    function extraData() public pure returns (bytes memory extraData_) {
        extraData_ = _getArgDynBytes(0x40, 0x20);
    }
```
`extraData` is of type `bytes`, which means it has unkown length.

As per the Sponsor:
```md
This is opaque data passed to the dispute game that's being created, which can be indexed by the clones-with-immutable-args proxy. 
In the case of the FDG, it's abi.encode(uint256(l2BlockNumber)), 
which is the L2 block number that the proposer claims that the submitted output root (the rootClaim) corresponds to 
```

The problem is that there is an assumption that the lenght of the bytes is `0x20`:
```javascript
    function extraData() public pure returns (bytes memory extraData_) {
        extraData_ = _getArgDynBytes(0x40, 0x20);
    }
```

When querying the `extraData`, `0x20` length gets returned, but it can be more than that.
This means that, if a Fault Dispute Game were to use the `_extraData` such that it has more than `0x20` bytes, only up until `0x20` bytes will be returned.
This leads to corrupted data which will break the game.

## Impact
Non-functionality of a fault dispute game if it implements `extraData` usage of more than length of `0x20` bytes.

## Code Snippet
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L87

## Tool used
Manual Review

## Recommendation
Limit the length of the `_extraData` parameter during the `create()` function.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10064
