### ISSUE TITLE
peanuts - Players in the DisputeGame can prevent other players from getting their rewards by frontrunning resolveClaim()

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#117]
peanuts

medium

# Players in the DisputeGame can prevent other players from getting their rewards by frontrunning resolveClaim()

## Summary

Players can prevent other players from getting rewards by frontrunning them and resolving the claim.

## Vulnerability Detail

To resolve a claim, anyone can call `resolveClaim()` and `resolve()` to change the status from `IN_PROGRESS` to either `DEFENDER_WINS` or `CHALLENGER_WINS`.

This is an example of how a player can grief another player through these two functions. To understand the game, must first understand `claimData` and `subgames`.

```solidity
ClaimData[] public claimData;
mapping(uint256 => uint256[]) internal subgames;
```

The first index of claimData, 0, is always created when the FaultDisputeGame instance is created in `initialize()`. This is the rootClaim, and there is no subgames yet.

```solidity
function initialize()
        // Set the root claim
        claimData.push(
            ClaimData({
                parentIndex: type(uint32).max,
                counteredBy: address(0),
                claimant: tx.origin,
                bond: uint128(msg.value),
                claim: rootClaim(),
                position: ROOT_POSITION,
                clock: LibClock.wrap(Duration.wrap(0), Timestamp.wrap(uint64(block.timestamp)))
            })
        );

        // Deposit the bond.
        WETH.deposit{ value: msg.value }();
```

The array of claimData[] is then increased with every `move()`, and the subgame with the corresponding index will be logged in the mapping.

```solidity
function move()
   // Create the new claim.
        claimData.push(
            ClaimData({
                parentIndex: uint32(_challengeIndex),
                // This is updated during subgame resolution
                counteredBy: address(0),
                claimant: msg.sender,
                bond: uint128(msg.value),
                claim: _claim,
                position: nextPosition,
                clock: nextClock
            })
        );

        // Update the subgame rooted at the parent claim.
        subgames[_challengeIndex].push(claimData.length - 1);
```

Take an example of a game with n depth and just 1 subgame, so root claim and one attack. Alice is the person that created the first claim (the root claim) and Bob is the person that attacks alice (attacking the left-most node).

claimData[0] is the root claim, and there is no subgame.

Bob calls `move()` with the intention to attack and the `challengeIndex` of 0 . claimData[1] is created with subgames[0] = [1]

There are no more claims, indicating that either Bob's attack wins or that the game has run out of time.

By right, Bob should call `resolveClaim()` with index 1, and since there are no subgames below the second claim, it implies that the parent claim is uncontested, and the bond should be returned to Bob.

```solidity
>      //@audit -- challengeIndices = subgames[1]
>      //@audit -- challengeIndicesLen = 0
   uint256[] storage challengeIndices = subgames[_claimIndex];
         uint256 challengeIndicesLen = challengeIndices.length;

        // INVARIANT: Cannot resolve subgames twice
        if (_claimIndex == 0 && subgameAtRootResolved) {
            revert ClaimAlreadyResolved();
        }

        // Uncontested claims are resolved implicitly unless they are the root claim. Pay out the bond to the claimant
        // and return early.
>      //@audit -- This if function is invoked since challengeIndicesLen is 0 and claimIndex is 1
        if (challengeIndicesLen == 0 && _claimIndex != 0) {
            // In the event that the parent claim is at the max depth, there will always be 0 subgames. If the
            // `counteredBy` field is set and there are no subgames, this implies that the parent claim was successfully
            // stepped against. In this case, we pay out the bond to the party that stepped against the parent claim.
            // Otherwise, the parent claim is uncontested, and the bond is returned to the claimant.
            address counteredBy = parent.counteredBy;
            address recipient = counteredBy == address(0) ? parent.claimant : counteredBy;
            _distributeBond(recipient, parent);
>           return;
        }
```

After Bob receives his claim, then `resolveClaim()` with claimIndex 0 will be called.

However, Alice can call resolveClaim with index 0 and resolve() in succession to prevent Bob from getting back his bond from his challenge claim.

When `resolveClaim(0)` is called, 

- challengeIndices = subgame[0] = [1];
- challengeIndicesLen = 1

```solidity
for (uint256 i = 0; i < challengeIndicesLen; ++i) {
           //@audit -- challengeIndex = [1][0] = 1
            uint256 challengeIndex = challengeIndices[i];

            // INVARIANT: Cannot resolve a subgame containing an unresolved claim
           //@audit -- subgames[1].length = 0
            if (subgames[challengeIndex].length != 0) revert OutOfOrderResolution();
           //@audit -- claimData[1] = Bob's Attack claim, where claimant == Bob
            ClaimData storage claim = claimData[challengeIndex];

            // If the child subgame is uncountered and further left than the current left-most counter,
            // update the parent subgame's `countered` address and the current `leftmostCounter`.
            // The left-most correct counter is preferred in bond payouts in order to discourage attackers
            // from countering invalid subgame roots via an invalid defense position. As such positions
            // cannot be correctly countered.
            // Note that correctly positioned defense, but invalid claimes can still be successfully countered.
           //@audit -- counteredBy == address(0), cliamant == Bob.
            if (claim.counteredBy == address(0) && leftmostCounter.raw() > claim.position.raw()) {
                countered = claim.claimant;
                leftmostCounter = claim.position;
            }
        }

        // If the parent was not successfully countered, pay out the parent's bond to the claimant.
        // If the parent was successfully countered, pay out the parent's bond to the challenger.
           //@audit -- Bond of first claim (Alice) distributed to Bob because Bob wins.
>       _distributeBond(countered == address(0) ? parent.claimant : countered, parent);

```

The bond is distributed to Bob, the subgames[0] array is deleted, and the `subgameAtRootResolved` becomes true. Then, resolve() is called immediately. 

```solidity
 /// @inheritdoc IDisputeGame
    function resolve() external returns (GameStatus status_) {
        // INVARIANT: Resolution cannot occur unless the game is currently in progress.
        if (status != GameStatus.IN_PROGRESS) revert GameNotInProgress();

        // INVARIANT: Resolution cannot occur unless the absolute root subgame has been resolved.
>       if (!subgameAtRootResolved) revert OutOfOrderResolution();

        // Update the global game status; The dispute has concluded.
        status_ = claimData[0].counteredBy == address(0) ? GameStatus.DEFENDER_WINS : GameStatus.CHALLENGER_WINS;
        resolvedAt = Timestamp.wrap(uint64(block.timestamp));

        // Update the status and emit the resolved event, note that we're performing an assignment here.
        emit Resolved(status = status_);

        // Try to update the anchor state, this should not revert.
        ANCHOR_STATE_REGISTRY.tryUpdateAnchorState();
    }
```

Since `subgameAtRootResolved` is now true, the status is changed to CHALLENGER_WINS and `resolveClaim()` cannot be called anymore because the status is no longer `IN_PROGRESS`

If one claim = 1 ETH (example), Alice makes the first claim and Bob makes the second claim, for a total of 2 ETH. If Bob wins the attack, he should get 2 ETH, but he only gets one.

## Impact

The player will get less ETH back than intended.

## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L386-L478

## Tool used

Manual Review

## Recommendation

Not sure about the recommendation, but make sure the challenger / defender is able to withdraw the bond of their own claim and the claim of their winners before resolving.

Duplicate of #164

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10148
