### ISSUE TITLE
John_Femi - Using the unlock will disable withdrawal of funds temporarily

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#129]
John_Femi

medium

# Using the unlock will disable withdrawal of funds temporarily

## Summary

On unlock, call funds lock temporarily, as bob cannot successfully call the withdraw function on alice's behalf and alice won't be able to withdraw until unlock is recalled with alice address.

## Vulnerability Detail

Alice-> bob is the idea which means Alice unlock her token with an arbitrary address, say Bob's address.

Alice might be able to withdraw her unlocked token in these scenarios
- calling the function withdraw(uint256 _wad) public override(WETH98, IWETH) to withdraw her token
- calling the function withdraw(address _guy, uint256 _wad) public to with her token

Following the ERC20 standard, withdraw function requires the amount to withdraw or amount to withdraw and recipient of withdrawal on the function withdrawal, the withdrawal function violates this standard and will cause DOS on users.

For example:
```solidity
function test_withdraw_whileUnlockedDelegate_succeeds() public {
        // Deposit some WETH.
        vm.prank(alice);
        delayedWeth.deposit{ value: 1 ether }();
        uint256 balance = address(alice).balance;

        // Unlock the withdrawal.
        vm.prank(alice);
        delayedWeth.unlock(bob, 1 ether);

        // Wait for the delay.
        vm.warp(block.timestamp + delayedWeth.delay() + 1);

        // Withdraw the WETH.
        vm.expectEmit(true, true, false, false);
        emit Withdrawal(address(alice), 1 ether);
        vm.prank(alice);
        delayedWeth.withdraw(1 ether);
        assertEq(address(alice).balance, balance + 1 ether);
    }
```

The function above will fail
`
Encountered 1 failing test in test/dispute/DelayedWETH.t.sol:DelayedWETH_Withdraw_Test
[FAIL. Reason: log != expected log] test_withdraw_whileUnlockedDelegate_succeeds() (gas: 66384)
`

The same will happen here at
```solidity
vm.prank(alice);
 delayedWeth.withdraw(alice, 1 ether);
 ```

Also putting bob as below and expecting bob as recipient of bob but receiving funds withdrawn in alice's wallet is a bug.
```solidity
vm.prank(alice);
delayedWeth.withdraw(bob, 1 ether);
```

## Impact
- DOS on users due to non-conformity to ERC20 EIP
- 

## Code Snippet

```solidity
function test_withdraw_whileUnlockedDelegate_succeeds() public {
        // Deposit some WETH.
        vm.prank(alice);
        delayedWeth.deposit{ value: 1 ether }();
        uint256 balance = address(alice).balance;

        // Unlock the withdrawal.
        vm.prank(alice);
        delayedWeth.unlock(bob, 1 ether);

        // Wait for the delay.
        vm.warp(block.timestamp + delayedWeth.delay() + 1);

        // Withdraw the WETH.
        vm.expectEmit(true, true, false, false);
        emit Withdrawal(address(alice), 1 ether);
        vm.prank(alice);
        delayedWeth.withdraw(1 ether);
        assertEq(address(alice).balance, balance + 1 ether);
    }
```

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/weth/DelayedWETH.sol#L57
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/weth/DelayedWETH.sol#L69
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/weth/DelayedWETH.sol#L74
## Tool used

Manual Review

## Recommendation
- Refactor the withdrawal to allow recipient with allowance and allow withdraw (uint_wad) work regardless of unlock arbitrary address.

**Comment by agbanusi** [comment]
> Invalid, withdrawals can only be invoked from the context of the withdrawer, there is no issue here

Regardless of the withdrawer context a user unlocking another address disables the user from withdrawing until the unlock function is recalled with the user's address already causing some DOS for the user is an issue I believe
