### ISSUE TITLE
OMEN - invalid L1 head will be load if reorg happened

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-optimism-2024-judging#134]
OMEN

medium

# invalid L1 head will be load if reorg happened

## Summary
wrong parent hash will be loaded at local data of oracle.
## Vulnerability Detail
There is a chance to occur reorg at ethereum mainnet . If this happened , transactions in that reorg will be rolled back.And also there will be different block hashing from previous one . This different block hash will leads to unintended problems for protocol . Dispute game factory create the dispute game with 3 immutable args by cloning the implemenation. 

    function create(
        GameType _gameType,
        Claim _rootClaim, //* bytes 32
        bytes calldata _extraData
    )
        external
        payable
        returns (IDisputeGame proxy_)
    {
     ....../
      bytes32 parentHash = blockhash(block.number - 1);
      proxy_ = IDisputeGame(address(impl).clone(abi.encodePacked(_rootClaim, parentHash, _extraData)));
      proxy_.initialize{ value: msg.value }();
      ...../ 
     }
## Impact
Invalid parent hash will be load at local data oracle
## Code Snippet
https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol#L103-L107

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L340-L342
## Tool used
manual view
Manual Review

## Recommendation
instead of using blockhash of previous block , using blockhash of last 5-10 blocks should be fine for reorg

**Comment by irving4444** [comment]
@nevillehuang can u also look at this issue?
