### ISSUE TITLE
laizy - the `initialize` function in `FaultDisputeGame` use `tx.origin` as claimant of the root claim

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-optimism-2024-judging#140]
laizy

medium

# the `initialize` function in `FaultDisputeGame` use `tx.origin` as claimant of the root claim

## Summary
the `initialize` function in `FaultDisputeGame` use `tx.origin` as claimant of the root claim, the real claimant should be the `msg.sender` of the factory contract. they will not be equal if `FaultDisputeGameFactory.create` is called by a smart contract, for example the user is using an abstract account , then `tx.origin` will be the bundler's address.

## Vulnerability Detail

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L555-L565

## Tool used

Manual Review

## Recommendation
change the function signature to `initialize(address _creator)` and the the factory pass the real creator to it.

**Comment by robinsdan** [comment]
@nevillehuang I think this issue reported the same thing as #194 , why #194 receives rewards but this one doest not? Since you have comfirmed it is valid: https://github.com/sherlock-audit/2024-02-optimism-2024-judging/issues/194#issuecomment-2081722836

**Comment by laizy** [comment]
@nevillehuang and @Evert0x Sorry to bother you.

> Invalid, no impact shown

I have already provided a detailed explanation regarding the situation with the AA wallet, where the claimant is erroneously set as the bundler. The claimant, by definition, is someone who has the authority to claim something (clearly the bond in this context) and it is set to the wrong user. Therefore, I believe I have sufficiently clarified the impact of the vulnerability.


I want to known why was my report not considered a valid duplication. Some people in the Discord group mentioned that I may have violated the [duplication rules](https://docs.sherlock.xyz/audits/judging/judging#ix.-duplication-rules).
> In addition to this, there is a submission **D** which identifies the core issue but does not clearly describe the impact or an attack path. Then **D** is considered low.

In English, 'does not A or B' means 'not A and not B'. Even disregarding the controversy regarding the impact of the vulnerability, I have still provided an attack path at the very least. Therefore, my report cannot be classified as Type D.

## Why didn't create an escalation during the escalation period? 
I am a newly registered user on this platform, and it is my first time to join the contest. After the contest ended, the website's page only mentioned that the status is in 'judging' without any further instructions. I checked the status every week, but there was no link on the page to notify me that I needed to communicate with the reviewers on GitHub. And I also check periodically if there are any new replies under the issue I submitted. I was not informed that my submitted report on Github was copied and pasted into a new repo, and the entire judgement process would not be reflected under my original issue. Therefore, I had no idea that my report was rejected, and I couldn't create an escalation in a timely manner.

I do not think it is solely my mistake. As a user, I have done my best and have not been negligent. If the admin had add a comment under my original issue and informed me the link to the new issue, or directly @ me in the new issue, then I would have received notifications from GitHub, and the current situation would not have arisen.
