### ISSUE TITLE
blockdev - `respectedGameTypeUpdatedAt` not set in `OptimismPortal2.initialize()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#30]
blockdev

high

# `respectedGameTypeUpdatedAt` not set in `OptimismPortal2.initialize()`

## Summary
For `0` game type, withdrawal claims created  the factory before `OptimismPortal2` was deployed or upgraded can be finalized.

## Vulnerability Detail
For `0` game type, `respectedGameTypeUpdatedAt` remains set to `0` as [`setRespectedGameType()`](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L451) doesn't need to be called. In this case, withdrawal claims created  before `OptimismPortal2` was deployed or upgraded can be finalized, since the [following check](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L451) always passes in [`checkWithdrawal()`](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L458C14-L458C29) function called in [`finalizeWithdrawalTransactionExternalProof()`](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L354):
```solidity
// The game must have been created after `respectedGameTypeUpdatedAt`. This is to prevent users from creating
// invalid disputes against a deployed game type while the off-chain challenge agents are not watching.
require(
    createdAt >= respectedGameTypeUpdatedAt,
    "OptimismPortal: dispute game created before respected game type was updated"
);
```

Here [`createdAt`](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/f216b0d3ad08c1a0ead557ea74691aaefd5fd489/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L473) is the timestamp at which the claim was created via the factory.

Note that the only way to update `disputeGameFactory` in `OptimismPortal2` is via its upgrade as there is no setter function. It can happen that the factory contract is deployed and after some time `OptimismPortal2` proxy upgrade happens to update `disputeGameFactory`.

Withdrawal claims created in this period shouldn't be finalized as off-chain challenge agents are not watching these claims. This is mentioned in the comments above too.

But since `respectedGameTypeUpdatedAt` is `0`, this check always succeeds finalizing those claims.

## Impact
Invalid withdrawal claims can be finalized.

## Code Snippet
```solidity
require(
    createdAt >= respectedGameTypeUpdatedAt,
    "OptimismPortal: dispute game created before respected game type was updated"
);
```

## Tool used

Manual Review

## Recommendation
Set `respectedGameTypeUpdatedAt` in `initializer()`:
```diff
function initialize(
    DisputeGameFactory _disputeGameFactory,
    SystemConfig _systemConfig,
    SuperchainConfig _superchainConfig
)
    public
    initializer
{
    disputeGameFactory = _disputeGameFactory;
    systemConfig = _systemConfig;
    superchainConfig = _superchainConfig;
+   respectedGameTypeUpdatedAt = uint64(block.timestamp);
    if (l2Sender == address(0)) {
        l2Sender = Constants.DEFAULT_L2_SENDER;
    }
    __ResourceMetering_init();
}
```

Duplicate of #85

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10198
