### ISSUE TITLE
0xdeadbeef - Execution of invalid messages due to missing initialization of `respectedGameTypeUpdatedAt`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#33]
0xdeadbeef

high

# Execution of invalid messages due to missing initialization of `respectedGameTypeUpdatedAt`

## Summary

Not setting `respectedGameTypeUpdatedAt` at `OptimismPortal2` initialization can bypass `checkWithdrawal` validation that the proven withdrawal was created after the game type was set. 

## Vulnerability Detail

`OptimismPortal2` has a mechanism that checks that a game was created after `respectedGameTypeUpdatedAt` to "prevent users from creating invalid disputes against a deployed game type while the off-chain challenge agents are not watching."
```solidity
        // The game must have been created after `respectedGameTypeUpdatedAt`. This is to prevent users from creating
        // invalid disputes against a deployed game type while the off-chain challenge agents are not watching.
        require(
            createdAt >= respectedGameTypeUpdatedAt,
            "OptimismPortal: dispute game created before respected game type was updated"
        );
```

It seems like challengers will only start disputing claims when `OptimismPortal2` is deployed/initialized. 

At `OptimismPortal2` initialization - the `respectedGameTypeUpdatedAt` and `respectedGameType` are not set. This seems intentional as `respectedGameType` for `CANNON` will be `0` so it will work without setting it. 

However - `respectedGameTypeUpdatedAt` will not be set and therefore `0`.

If:
1. The `FaultDisputeGame` is deployed before the `OptimismPortal2` is initialized
2. Challengers and guardians look only at claims since the `OptimismPortal2` is initialized
 
Then - a malicious actor can prove an invalid withdrawal against a falsely resolved claim (since it has not been challenged) and finalize the invalid transaction.

## Impact

Execution of invalid withdrawal
 
## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L504-L507

## Tool used

Manual Review

## Recommendation

Consider at initialization to set the `respectedGameTypeUpdatedAt` and `respectedGameType` 

Duplicate of #85

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10198
