### ISSUE TITLE
haxatron - `respectedGameTypeUpdatedAt` is uninitialized which can bypass off-chain monitors

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-optimism-2024-judging#76]
haxatron

medium

# `respectedGameTypeUpdatedAt` is uninitialized which can bypass off-chain monitors

## Summary

`respectedGameTypeUpdatedAt` is uninitialized 

## Vulnerability Detail

In the `initialize` function, the `respectedGameTypeUpdatedAt` is not initialized so it is 0 on contract deployment.

[OptimismPortal2.sol#L147-L162](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L147-L162)
```solidity
    function initialize(
        DisputeGameFactory _disputeGameFactory,
        SystemConfig _systemConfig,
        SuperchainConfig _superchainConfig
    )
        public
        initializer
    {
        disputeGameFactory = _disputeGameFactory;
        systemConfig = _systemConfig;
        superchainConfig = _superchainConfig;
        if (l2Sender == address(0)) {
            l2Sender = Constants.DEFAULT_L2_SENDER;
        }
        __ResourceMetering_init();
    }
```

These checks are important on withdrawal finalization, because if not users can create invalid disputes against a deployed game type while the off-chain monitors are not watching. Therefore in case a user can create dispute games before the OptimismPortal2 is launched, it may be possible to bypass these off-chain monitors

[OptimismPortal2.sol#L458-L519](https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L458-L519)
```solidity
    function checkWithdrawal(bytes32 _withdrawalHash, address _proofSubmitter) public view {
        ProvenWithdrawal memory provenWithdrawal = provenWithdrawals[_withdrawalHash][_proofSubmitter];
        IDisputeGame disputeGameProxy = provenWithdrawal.disputeGameProxy;

        ...
        // The game must have been created after `respectedGameTypeUpdatedAt`. This is to prevent users from creating
        // invalid disputes against a deployed game type while the off-chain challenge agents are not watching.
        require(
            createdAt >= respectedGameTypeUpdatedAt,
            "OptimismPortal: dispute game created before respected game type was updated"
        );
        ...
    }
```
## Impact

`respectedGameTypeUpdatedAt` is uninitialized which can bypass off-chain monitors

## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/L1/OptimismPortal2.sol#L147-L162

## Tool used

Manual Review

## Recommendation

Initialize `respectedGameTypeUpdatedAt`.

Duplicate of #85

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10198
