### ISSUE TITLE
GalloDaSballo - `tx.origin` breaks ability to have someone else broadcast TXs and may cause loss of bonds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#96]
GalloDaSballo

medium

# `tx.origin` breaks ability to have someone else broadcast TXs and may cause loss of bonds

## Summary

The use of `tx.origin` adds an additional risk to the bonding system that can be avoided by passing the `payer` in `initialize`

## Impact

The `FaultDisputeGame.initialize` sets the starting `claimData` as follows:

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L555-L565

```solidity
        claimData.push(
            ClaimData({
                parentIndex: type(uint32).max,
                counteredBy: address(0),
                claimant: tx.origin,
                bond: uint128(msg.value),
                claim: rootClaim(),
                position: ROOT_POSITION,
                clock: LibClock.wrap(Duration.wrap(0), Timestamp.wrap(uint64(block.timestamp)))
            })
        );
```

Setting the claimant to `tx.origin` this can be used to:
- Steal a benign claimant bond by "sponsoring" their tx
- Makes the system incompatible with Account Abstraction
- Creates issues for Keepers (as the fee will be attributed to them instead of the actual payer)

The rest of the system doesn't prevent SCs or SC Wallets from interacting with it, but this setting does break composability

## Code Snippet

- User A wants to get their withdrawals proven automatically by a 3rd party service
- The third party service will have their relayers EOAs steal funds and force them to work via a trusted system
- The third party EOA will be `tx.origin`, user a will pay the bond and not be guaranteed to receive it back

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L559-L560

## Tool used

Manual Review

## Recommendation

A simple refactoring that forwards the original `payer` or specifying a `bondReceiver` would be sufficient in this case

Duplicate of #194

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10149
