### ISSUE TITLE
zraxx - The time window for dispute of a claim can be short, allowing attackers to quickly win the bond.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-optimism-2024-judging#99]
zraxx

medium

# The time window for dispute of a claim can be short, allowing attackers to quickly win the bond.

## Summary

The time window for dispute of a claim can be short, allowing attackers to quickly win the bond.

## Vulnerability Detail

In the function move, there is a check for duration that duration can’t exceed the GAME_DURATION / 2, which means the maximum duration is GAME_DURATION / 2.

```solidity
// INVARIANT: A move can never be made once its clock has exceeded `GAME_DURATION / 2`
//            seconds of time.
if (nextDuration.raw() > GAME_DURATION.raw() >> 1) revert ClockTimeExceeded();
```

Then, in the function resolveClaim, there is a check that user can’t resolve a subgame unless the clock of its root has expired.

```solidity
// INVARIANT: Cannot resolve a subgame unless the clock of its root has expired
uint64 parentClockDuration = parent.clock.duration().raw();
uint64 timeSinceParentMove = uint64(block.timestamp) - parent.clock.timestamp().raw();
if (parentClockDuration + timeSinceParentMove <= GAME_DURATION.raw() >> 1) {
    revert ClockNotExpired();
}
```

As parentClockDuration can be GAME_DURATION / 2, which means that this check can be bypassed as long as timeSinceParentMove is greater than 0.

As a result, an attacker can quickly win the bonds by disputing these claims which have a very short dispute window.

## Impact

Bonds will be stolen by attackers

## Code Snippet

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L284

https://github.com/sherlock-audit/2024-02-optimism-2024/blob/main/optimism/packages/contracts-bedrock/src/dispute/FaultDisputeGame.sol#L412-L416

## Tool used

Manual Review

## Recommendation

Increase dispute window for claims.

Duplicate of #8

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/ethereum-optimism/optimism/pull/10148
